modules:
  default:
    user: <username>
    pass: <password>
    driver: "LAN_2_0" # see man 8 ipmi-sensors
    privilege: "user" # see man 5 freeipmi.conf
    timeout: 10000
    collectors:
      - bmc
      - ipmi
      - chassis
