- name: Assert that baremetal_observability_inventory_service is defined and not empty
  ansible.builtin.assert:
    that:
      - baremetal_observability_inventory_service is defined
      - baremetal_observability_inventory_service != ""
    fail_msg: "Variable 'baremetal_observability_inventory_service' is either not defined or is empty."
    quiet: true

- name: Assert that baremetal_observability_exporters is defined and not empty
  ansible.builtin.assert:
    that:
      - baremetal_observability_exporters is defined
      - baremetal_observability_exporters | length > 0
    fail_msg: "Variable 'baremetal_observability_exporters' is either not defined or is empty."
    quiet: true

# Expected variables to be registered:
#
# name: bmc_endpoints
# type: []string
# description: a string of format <BMC hostname/IP address>:<BMC port>
- name: Get BMC addresses with ports
  ansible.builtin.import_role:
    name: "{{ baremetal_observability_inventory_service }}"

- name: Assert variable 'bmc_endpoints' is defined and not empty
  ansible.builtin.assert:
    that:
      - bmc_endpoints is defined
      - bmc_endpoints | length > 0
    fail_msg: "Variable 'bmc_endpoints' is either not defined or is empty.
    The role {{ baremetal_observability_inventory_service }} should register the variable before completion."
    quiet: true

- name: Create baremetal_observability namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ baremetal_observability_namespace }}"
        labels:
          openshift.io/cluster-monitoring: "true"

- name: Deploy metric exporters
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop: "{{ baremetal_observability_exporters | default([]) }}"
