- name: Create the system to monitor for baremetal metrics
  when: baremetal_observability_state == 'present'
  ansible.builtin.include_tasks: create_baremetal_observability.yaml

- name: Destroy the system to monitor for baremetal metrics
  when: baremetal_observability_state == 'absent'
  ansible.builtin.include_tasks: destroy_baremetal_observability.yaml
