- name: Get all baremetal nodes
  openstack.cloud.baremetal_info:
  register: baremetal_nodes

- name: Extract all ipmi_addresses
  set_fact:
    ipmi_addresses: "{{ baremetal_nodes.baremetals | map(attribute='driver_info.ipmi_address') | list }}"

- name: Create baremetal_observability namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    metadata:
      name: "{{ baremetal_observability_namespace }}"
      labels:
        openshift.io/cluster-monitoring: "true"

- name: Deploy IPMI exporter
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ipmi-exporter
        namespace: "{{ baremetal_observability_namespace }}"
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: ipmi-exporter
          template:
             metadata:
               labels:
                 app: ipmi-exporter
             spec:
               containers:
               - name: ipmi-exporter
                 image: quay.io/prometheuscommunity/ipmi-exporter:latest
                 args:
                   - "--config.file=/config/ipmi-exporter-config.yaml"
                 ports:
                 - containerPort: 9290
                   name: ipmi-metrics
                 volumeMounts:
                 - name: ipmi-exporter-config
                   mountPath: /config
               volumes:
               - name: ipmi-exporter-config
                 secret:
                   secretName: ipmi-exporter-config

- name: Create IPMI exporter service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: ipmi-exporter
        namespace: "{{ baremetal_observability_namespace }}"
      spec:
        selector:
          app: ipmi-exporter
        ports:
          - name: http
            port: 9290
            targetPort: ipmi-metrics

- name: Create service monitor for IPMI exporter
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: ipmi-service-monitor
        namespace: "{{ baremetal_observability_namespace }}"
        labels:
          openshift.io/cluster-monitoring: "true"
      spec:
        selector:
          matchLabels:
            app: ipmi-exporter
        namespaceSelector:
          matchNames:
            - "{{ baremetal_observability_namespace }}"
        endpoints:
          - port: http
            path: /ipmi
            interval: 60s
            params:
              module: [default]
            static_configs:
              - targets: {{ ipmi_addresses | to_json }}
            relabelings:
              - sourceLabels: [__address__]
                targetLabel: __param_target
              - sourceLabels: [__param_target]
                targetLabel: instance
              - targetLabel: __address__
                replacement: ipmi-exporter.{{ baremetal_observability_namespace }}.svc.cluster.local:9290

